kind: Deployment
apiVersion: apps/v1
metadata: 
  name: auth-deployment
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 1

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app: auth 
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: auth 
    spec:
      imagePullSecrets:
        - name: regcred      
      containers:
        - name: auth 
          image: nouveaulabs/vc_auth:LATEST
          imagePullPolicy: Always
          ports:
                  - containerPort: 4001
                    protocol: TCP
          env:
            - name: SMS_API  
              value: "0nZjhxQWbfY-lfMu93PKuAw88moHEEeXAftsMKweho"
            - name: EMAIL_PASSWORD
              value: "I@mgod456"
            - name: FUSIONAUTH_URL
              value: "http://demo.ask-ai.ml:9011"
            - name: FUSIONAUTH_API_KEY
              value: "mpLXdQQpQPTVAoBEDrg7U6_-_MLf_svHNCpU56ceMp8"
            - name: APPLICATION_ID
              value: "2ea97e39-dc5c-4207-af1a-ccdb1f7bf819"
            - name: DEFAULT_PASSWORD_PHONE
              value: "defaultDolphin"
            - name: SENDER_EMAIL
              value: "no-reply@dolphinvc.com"
            - name: EMAIL_SERVER
              value: "smtpout.secureserver.net"
            - name: EMAIL_PORT
              value: "587"
            - name: REDIS_URL
              value: "general.ask-ai.ml"
            - name: REDIS_PASSWORD
              value: "n0uve@ulabs"
            - name: GOOGLE_CLIENT_ID
              value: "840400962744-l7rlj8jli02eak8k48aacn6pth3fhpm5.apps.googleusercontent.com"
            - name: GOOGLE_CLIENT_SECRET
              value: "ZMlGzjamM417TMgknosuS1oG"
            - name: GOOGLE_IDENTITY_PROVIDER_ID
              value: "82339786-3dff-42a6-aac6-1f1ceecb6c46"
            - name: FACEBOOK_APP_ID
              value: "1292294940977645"
            - name: FACEBOOK_APP_SECRET
              value: "b38be988a918431c597eb06b1719ba85"
            - name: FACEBOOK_IDENTITY_PROVIDER_ID
              value: "56abdcc7-8bd9-4321-9621-4e9bbebae494" 
            - name: PORT  
              value: "4001"
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth 
spec:
  type: NodePort
  ports:
  - port: 4001 
    targetPort: 4001 
    nodePort: 30001
  selector:
    app: auth 

