kind: Deployment
apiVersion: apps/v1
metadata: 
  name: db-deployment
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 1 

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app: db 
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template: 
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: db
    spec:
      imagePullSecrets:
        - name: regcred    
      containers:
        - name: db
          image: nouveaulabs/dbservice:LATEST
          imagePullPolicy: Always
          ports:
                  - containerPort: 4000
                    protocol: TCP        
          env: 
            - name: PORT  
              value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service 
  labels:
    app: db
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30010
  selector:
    app: db 
