kind: Deployment
apiVersion: apps/v1
metadata: 
  name: fusion-deployment
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 1

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app: fusionapp
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: fusionapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: fusionapp
          image: nouveaulabs/fusionapp:LATEST
          imagePullPolicy: Always
          ports:
                  - containerPort: 9011
                    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fusionapp
  labels:
    app: fusionapp
spec:
  type: NodePort
  ports:
  - port: 9011
    targetPort: 9011
    nodePort: 30060
  selector:
    app: fusionapp
