kind: Deployment
apiVersion: apps/v1
metadata: 
  name: smsgateway-deployment
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 1

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app: smsgw 
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: smsgw 
    spec:
      imagePullSecrets:
        - name: regcred      
      containers:
        - name: smsgateway 
          image: nouveaulabs/smsgateway:LATEST 
          imagePullPolicy: Always
          ports:
                  - containerPort: 5050           
                    protocol: TCP
          env:
            - name: KEY  
              value: "0nZjhxQWbfY-lfMu93PKuAw88moHEEeXAftsMKweho" 
            - name: PORT  
              value: "5050"
            - name: SENDER 
              value: "TXTLCL"
---
apiVersion: v1
kind: Service
metadata:
  name: smsgw 
  labels:
    app: smsgw 
spec:
  type: NodePort
  ports:
  - port: 5050 
    targetPort: 5050 
    nodePort: 30050
  selector:
    app: smsgw 
